# Generated by Django 2.0.7 on 2018-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dt_end',
            field=models.DateTimeField(default=None, verbose_name='Время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dt_start',
            field=models.DateTimeField(default=None, verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступно для оцифровки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='UID события'),
        ),
    ]
