# Generated by Django 2.0.7 on 2018-07-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0003_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveIntegerField(db_index=True)),
                ('trace_type', models.CharField(db_index=True, max_length=255)),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmaterial',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Trace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unti_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='events',
            field=models.ManyToManyField(to='isle.Event'),
        ),
    ]
