# Generated by Django 2.0.7 on 2018-07-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeamMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('comment', models.CharField(default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Team')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Trace')),
            ],
            options={
                'verbose_name': 'Материал команды',
                'verbose_name_plural': 'Материалы команд',
            },
        ),
    ]
