# Generated by Django 2.0.7 on 2018-07-09 11:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0007_eventonlymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний id')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('trace_data', jsonfield.fields.JSONField(blank=True, help_text='JSON в виде списка из объектов с ключами trace_type и name. Например, [{"trace_type": "Презентация", "name": "Презентация продукта"}]')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятия',
            },
        ),
        migrations.AlterModelOptions(
            name='trace',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='trace',
            name='events',
            field=models.ManyToManyField(blank=True, to='isle.Event', verbose_name='События'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='ext_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='trace_type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isle.EventType', verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='trace',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isle.EventType', verbose_name='Тип мероприятия'),
        ),
    ]
