# Generated by Django 2.0.7 on 2018-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0008_auto_20180709_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ile_id',
            field=models.PositiveIntegerField(default=None, verbose_name='id в ILE'),
        ),
    ]
