# Generated by Django 2.0.7 on 2018-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0010_event_ext_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='added_by_assistant',
            field=models.BooleanField(default=False, verbose_name='Добавлен вручную'),
        ),
    ]
