# Generated by Django 2.0.7 on 2018-07-14 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0012_evententry_check_in_pushed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('confirmed_by_system', models.CharField(choices=[('uploads', 'uploads'), ('chat_bot', 'chat_bot')], max_length=255)),
                ('is_confirmed', models.BooleanField()),
                ('confirmed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_by_user', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user')},
        ),
    ]
