# Generated by Django 2.0.7 on 2018-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0013_auto_20180715_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaterial',
            name='file',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventonlymaterial',
            name='file',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventteammaterial',
            name='file',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
    ]
