# Generated by Django 2.0.7 on 2018-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0014_auto_20180715_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaterial',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
