# Generated by Django 2.0.7 on 2018-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0016_auto_20180717_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
