# Generated by Django 2.0.7 on 2018-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0017_user_leader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
