# Generated by Django 2.0.7 on 2018-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0018_evententry_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaterial',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
