# Generated by Django 2.0.7 on 2018-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0019_eventmaterial_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteammaterial',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
