# Generated by Django 2.0.7 on 2018-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0020_eventteammaterial_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='approve_text',
            field=models.TextField(blank=True, default='', verbose_name='Подтверждающий текст'),
        ),
    ]
