# Generated by Django 2.0.7 on 2018-07-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0020_eventteammaterial_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
