# Generated by Django 2.0.7 on 2018-07-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0022_auto_20180719_1911'),
        ('isle', '0021_evententry_approve_text'),
    ]

    operations = [
    ]
