# Generated by Django 2.0.7 on 2018-08-02 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0024_auto_20180721_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('ile_id', models.PositiveIntegerField(default=None, verbose_name='id в ILE')),
                ('ext_id', models.PositiveIntegerField(db_index=True, default=None, verbose_name='id в LABS')),
                ('title', models.CharField(max_length=1000)),
                ('main_author', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='isle.Activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activityenrollment',
            unique_together={('user', 'activity')},
        ),
    ]
