# Generated by Django 2.0.7 on 2018-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0025_auto_20180802_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaterial',
            name='file_size',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventmaterial',
            name='file_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventonlymaterial',
            name='file_size',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventonlymaterial',
            name='file_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventteammaterial',
            name='file_size',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventteammaterial',
            name='file_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
