# Generated by Django 2.0.7 on 2018-08-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0025_auto_20180802_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
