# Generated by Django 2.0.7 on 2018-08-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0026_auto_20180803_2055'),
        ('isle', '0026_activity_is_deleted'),
    ]

    operations = [
    ]
