# Generated by Django 2.0.7 on 2018-08-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0030_auto_20180809_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventonlymaterial',
            name='event_block',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isle.EventBlock'),
        ),
        migrations.AddField(
            model_name='eventonlymaterial',
            name='related_teams',
            field=models.ManyToManyField(blank=True, related_name='connected_materials', to='isle.Team'),
        ),
        migrations.AddField(
            model_name='eventonlymaterial',
            name='related_users',
            field=models.ManyToManyField(blank=True, related_name='connected_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventblock',
            name='duration',
            field=models.IntegerField(verbose_name='Минут'),
        ),
        migrations.AlterField(
            model_name='eventblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='teamresult',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 – слабый результат'), (2, '2 – нормальный результат'), (3, '3 – отличный результат')], null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 – слабый результат'), (2, '2 – нормальный результат'), (3, '3 – отличный результат')], null=True, verbose_name='Оценка'),
        ),
    ]
