# Generated by Django 2.0.7 on 2018-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0031_auto_20180810_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaterial',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventonlymaterial',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventteammaterial',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),

        migrations.AlterField(
            model_name='eventmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventonlymaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventteammaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
