# Generated by Django 2.0.7 on 2018-10-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0035_eventtype_visible'),
        ('isle', '0035_auto_20181012_0346'),
    ]

    operations = [
    ]
