# Generated by Django 2.0.7 on 2018-11-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0036_merge_20181016_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabsEventBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('block_type', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LabsEventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('title', models.TextField()),
                ('result_format', models.CharField(max_length=50)),
                ('fix', models.TextField()),
                ('check', models.TextField()),
                ('order', models.IntegerField()),
                ('meta', jsonfield.fields.JSONField(default=None, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='isle.LabsEventBlock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LabsUserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('approved', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.LabsEventResult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventtype',
            name='uuid',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='ext_id',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True, verbose_name='id в LABS'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ext_id',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='id в LABS'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='ext_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Внешний id'),
        ),
        migrations.AddField(
            model_name='labseventblock',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='isle.Event'),
        ),
        migrations.AddField(
            model_name='eventmaterial',
            name='result_v2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isle.LabsUserResult'),
        ),
        migrations.AlterUniqueTogether(
            name='labsuserresult',
            unique_together={('user', 'result')},
        ),
    ]
