# Generated by Django 2.0.7 on 2019-02-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0040_metamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_context',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isle.Context'),
        ),
    ]
