# Generated by Django 2.0.7 on 2019-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0042_auto_20190212_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='labseventblock',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labseventresult',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trace',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
