# Generated by Django 2.0.7 on 2019-03-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0043_auto_20190214_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, max_length=300, upload_to='')),
                ('file_type', models.CharField(default='', max_length=1000)),
                ('file_size', models.PositiveIntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PLEUserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('meta', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='ple_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.PLEUserResult'),
        ),
    ]
