# Generated by Django 2.0.7 on 2019-03-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0043_auto_20190214_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_uuid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContextRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.ContextRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='ct_type',
            field=models.CharField(choices=[('open', 'Открытый'), ('closed', 'Закрытый')], default='open', max_length=30, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='context',
            name='datetime_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AddField(
            model_name='context',
            name='datetime_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время начала'),
        ),
        migrations.AddField(
            model_name='context',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='context',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='context',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='isle.Context', verbose_name='Контекст верхнего уровня'),
        ),
        migrations.AddField(
            model_name='context',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('draft', 'Черновик'), ('archive', 'Архивный'), ('ended', 'Завершен'), ('deleted', 'Удален')], default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='context',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='context',
            name='guid',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contextrole',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontextrole',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='contextrole',
            unique_together={('context_uuid', 'tag')},
        ),
    ]
