# Generated by Django 2.0.7 on 2019-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0043_auto_20190214_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('is_main', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='authors',
            field=models.ManyToManyField(to='isle.Author'),
        ),
    ]
