# Generated by Django 2.0.7 on 2019-04-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0044_auto_20190328_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_uuid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContextRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.ContextRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contextrole',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontextrole',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='contextrole',
            unique_together={('context_uuid', 'tag')},
        ),
    ]
