# Generated by Django 2.0.7 on 2019-05-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0045_auto_20190508_1930'),
        ('isle', '0045_userfile'),
    ]

    operations = [
    ]
