# Generated by Django 2.0.7 on 2019-05-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0045_dpcompetence'),
        ('isle', '0046_merge_20190523_2034'),
    ]

    operations = [
    ]
