# Generated by Django 2.0.7 on 2019-06-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0047_merge_20190529_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLEUserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('meta', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userfile',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_size',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userfile',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
        migrations.AddField(
            model_name='userfile',
            name='ple_result',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='isle.PLEUserResult'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
