# Generated by Django 2.0.7 on 2019-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0049_auto_20190525_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='self_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
