# Generated by Django 2.0.7 on 2019-07-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0050_evententry_self_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contexts',
            field=models.ManyToManyField(to='isle.Context'),
        ),
        migrations.AddField(
            model_name='team',
            name='system',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isle.Event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
