# Generated by Django 2.0.7 on 2019-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0051_auto_20190703_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_head', models.TextField(blank=True, default='', verbose_name='Код до закрывающегося тега head')),
                ('before_body', models.TextField(blank=True, default='', verbose_name='Код после открывающегося тега body')),
            ],
            options={
                'verbose_name': 'Виджет zendesk',
                'verbose_name_plural': 'Виджет zendesk',
            },
        ),
    ]
