# Generated by Django 2.0.7 on 2019-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0052_zendeskdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTimes',
            fields=[
                ('event_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
