# Generated by Django 2.0.7 on 2019-07-18 09:17

from django.db import migrations, models


def set_approved_none(apps, schema_editor):
    LabsUserResult = apps.get_model('isle', 'LabsUserResult')
    LabsTeamResult = apps.get_model('isle', 'LabsTeamResult')
    for model in (LabsUserResult, LabsTeamResult):
        model.objects.update(approved=None)


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0053_auto_20190717_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsteamresult',
            name='approve_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='labsuserresult',
            name='approve_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='labsteamresult',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='labsuserresult',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
        migrations.RunPython(set_approved_none, reverse_code=migrations.RunPython.noop)
    ]
