# Generated by Django 2.0.7 on 2019-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0053_updatetimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenrollment',
            name='created',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='runenrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
