# Generated by Django 2.0.7 on 2019-07-19 15:55

from django.db import migrations, models
import django.db.models.deletion
from isle.utils import create_circle_items_for_result


def fix_circle_items(apps, schema):
    """
    создание CircleItem по метаданным из LabsEventResult и проставление их существующим
    объектам LabsUserResult и LabsTeamResult
    запросы в кафку не будут посылаться при выполнении миграции т.к. структура мероприятия не будет изменена
    """
    DpCompetence = apps.get_model('isle', 'DpCompetence')
    MetaModel = apps.get_model('isle', 'MetaModel')
    LabsEventResult = apps.get_model('isle', 'LabsEventResult')
    LabsUserResult = apps.get_model('isle', 'LabsUserResult')
    LabsTeamResult = apps.get_model('isle', 'LabsTeamResult')
    competence_uuid_to_id = dict(DpCompetence.objects.values_list('uuid', 'id'))
    model_uuid_to_id = dict(MetaModel.objects.values_list('uuid', 'id'))
    for res in LabsEventResult.objects.filter(meta__isnull=False):
        if res.meta and isinstance(res.meta, list):
            circle_items_ids = create_circle_items_for_result(
                res.id,
                list(res.circle_items.values_list('id', flat=True)),
                res.meta,
                model_uuid_to_id,
                competence_uuid_to_id
            )
            for result_model in (LabsUserResult, LabsTeamResult):
                for result in result_model.objects.filter(result=res).iterator():
                    result.circle_items.set(circle_items_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0054_auto_20190718_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=None, null=True)),
                ('sublevel', models.IntegerField(default=None, null=True)),
                ('tool', models.TextField(default=None, null=True)),
                ('competence', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='isle.DpCompetence')),
                ('model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='isle.MetaModel')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_items', to='isle.LabsEventResult')),
            ],
        ),
        migrations.AddField(
            model_name='labsteamresult',
            name='circle_items',
            field=models.ManyToManyField(to='isle.CircleItem'),
        ),
        migrations.AddField(
            model_name='labsuserresult',
            name='circle_items',
            field=models.ManyToManyField(to='isle.CircleItem'),
        ),
        migrations.RunPython(fix_circle_items, reverse_code=migrations.RunPython.noop),
    ]
