# Generated by Django 2.0.7 on 2019-07-22 15:38

import hashlib
from django.db import migrations, models


def delete_duplicates_and_update_fields(apps, schema):
    CircleItem = apps.get_model('isle', 'CircleItem')
    LabsUserResult = apps.get_model('isle', 'LabsUserResult')
    LabsTeamResult = apps.get_model('isle', 'LabsTeamResult')
    qs = CircleItem.objects.values('level', 'sublevel', 'model', 'competence', 'result', 'tool').annotate(
        cnt=models.Count('id')).filter(cnt__gt=1)
    # удаление дубликатов
    for item in qs.iterator():
        data = item.copy()
        data.pop('cnt', None)
        items = list(CircleItem.objects.filter(**data))
        main_item = items[0]
        for fix_item in items[1:]:
            for result_model in (LabsUserResult, LabsTeamResult):
                for result_item in result_model.objects.filter(circle_items=fix_item).distinct().iterator():
                    result_item.circle_items.add(main_item)
            fix_item.delete()

    # обновление полей с проставлением уникального поля code для CircleItem
    for item in CircleItem.objects.select_related('competence', 'model').iterator():
        competence_uuid = item.competence.uuid if item.competence else ''
        model_uuid = item.model.uuid if item.model else ''
        code = ':'.join([
            str(item.level),
            str(item.sublevel),
            str(competence_uuid),
            str(model_uuid),
            str(item.result_id),
            str(item.tool),
        ])
        code = hashlib.md5(code.encode('utf8')).hexdigest()
        CircleItem.objects.filter(pk=item.pk).update(
            competence_uuid=competence_uuid,
            model_uuid=model_uuid,
            code=code,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0055_auto_20190720_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleitem',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='circleitem',
            name='competence_uuid',
            field=models.CharField(default=None, null=True, max_length=36),
        ),
        migrations.AddField(
            model_name='circleitem',
            name='model_uuid',
            field=models.CharField(default=None, null=True, max_length=36),
        ),
        migrations.RunPython(delete_duplicates_and_update_fields, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='circleitem',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
