# Generated by Django 2.0.7 on 2019-07-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0055_auto_20190720_0155'),
        ('isle', '0054_runenrollment_created'),
    ]

    operations = [
    ]
