# Generated by Django 2.0.7 on 2019-07-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0056_auto_20190723_0138'),
        ('isle', '0056_merge_20190722_2350'),
    ]

    operations = [
    ]
