# Generated by Django 2.0.7 on 2019-10-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0059_auto_20190817_0042'),
        ('isle', '0057_merge_20190724_2350'),
        ('isle', '0059_auto_20191022_2151'),
    ]

    operations = [
    ]
