# Generated by Django 2.0.7 on 2019-10-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0060_merge_20191025_1838'),
        ('isle', '0060_merge_20191025_2046'),
    ]

    operations = [
    ]
