# Generated by Django 2.0.7 on 2019-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0061_merge_20191029_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='casbindata',
            name='model_version',
            field=models.IntegerField(default=1),
        ),
    ]
