# Generated by Django 2.0.7 on 2019-11-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0062_casbindata_model_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcompetence',
            name='type',
        ),
        migrations.AddField(
            model_name='dpcompetence',
            name='type',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
