# Generated by Django 2.0.7 on 2019-12-03 14:12

from django.db import migrations, models
import isle.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0063_auto_20191108_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaterial',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventonlymaterial',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventteammaterial',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='labsteamresult',
            name='comment',
            field=isle.fields.SafeUTF8Text(default=''),
        ),
        migrations.AlterField(
            model_name='labsuserresult',
            name='comment',
            field=isle.fields.SafeUTF8Text(default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=isle.fields.SafeUTF8Text(blank=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
